

[general]
live_config_reload = true

[font]
size = 18

[font.normal]
family = "UbuntuMono Nerd Font Mono"
style = "Regular"

[window]
dynamic_title = true

[keyboard]
bindings = [
  { key = "Return", action = "CreateNewWindow", mods = "Control|Shift" },
  { chars = "\u001Bb", key = "Left", mods = "Alt" },
  { chars = "\u001Bf", key = "Right", mods = "Alt" },
  { chars = "\u001BOH", key = "Left", mode = "AppCursor", mods = "Command" },
  { chars = "\u001BOF", key = "Right", mode = "AppCursor", mods = "Command" },
  { chars = "\u0015", key = "Back", mods = "Command" },
  { chars = "\u001B\u007F", key = "Back", mods = "Alt" }
]
